"""initial schema

Revision ID: 1e21f72d02e6
Revises: 
Create Date: 2026-05-15 16:20:21.205934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e21f72d02e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'record_id', name='uq_regulatory_record_source_record_id')
    )
    op.create_index(op.f('ix_regulatory_records_record_id'), 'regulatory_records', ['record_id'], unique=False)
    op.create_index(op.f('ix_regulatory_records_source'), 'regulatory_records', ['source'], unique=False)
    op.create_table('webhook_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('callback_url', sa.String(length=2048), nullable=False),
    sa.Column('agencies', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('new_hash', sa.String(length=64), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['regulatory_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_record_id'), 'change_events', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_events_record_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_table('webhook_registrations')
    op.drop_index(op.f('ix_regulatory_records_source'), table_name='regulatory_records')
    op.drop_index(op.f('ix_regulatory_records_record_id'), table_name='regulatory_records')
    op.drop_table('regulatory_records')
    # ### end Alembic commands ###
